version: '3'

volumes:
  pemors_local_postgres_data: {}
  pemors_local_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: pemors_local_django
    container_name: pemors_local_django
    platform: linux/x86_64
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start
    tty: true

  tailwind:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: pemors_local_django
    container_name: pemors_local_tailwind
    platform: linux/x86_64
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    command: bash -c "npm run dev"
    working_dir: /app/theme/static_src
    # Without tty, no stdin, and tailwind watcher aborts
    # https://github.com/tailwindlabs/tailwindcss/issues/5324
    tty: true

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: pemors_production_postgres
    container_name: pemors_local_postgres
    volumes:
      - pemors_local_postgres_data:/var/lib/postgresql/data:Z
      - pemors_local_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.local/.postgres
