# Generated by Django 4.0.3 on 2022-06-04 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='agr',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='con',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ext',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='neu',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='opn',
            field=models.FloatField(default=0),
        ),
    ]
