# Generated by Django 3.2.15 on 2022-10-01 15:45

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220930_0305'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='recommender',
            field=picklefield.fields.PickledObjectField(editable=False, null=True),
        ),
    ]
