# Generated by Django 3.2.15 on 2022-10-13 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20221012_2346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='recommender',
        ),
    ]
