# Generated by Django 3.2.15 on 2022-10-13 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_profile_recommender'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='users_user_rating__437479_idx',
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(condition=models.Q(('rating_counter__gte', 10)), fields=['rating_counter'], name='$(app_label)s_$(class)s_valid'),
        ),
    ]
