# Generated by Django 3.2.15 on 2022-10-15 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20221013_0444'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='$(app_label)s_$(class)s_valid',
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(condition=models.Q(('rating_counter__gte', 20)), fields=['rating_counter'], name='$(app_label)s_$(class)s_valid'),
        ),
    ]
