# Generated by Django 4.0.3 on 2022-05-28 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False, unique=True)),
                ('primary_name', models.CharField(max_length=256)),
                ('birth_year', models.IntegerField(null=True)),
                ('death_year', models.IntegerField(null=True)),
                ('profession', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(max_length=32)),
                ('primary_title', models.CharField(max_length=512)),
                ('original_title', models.CharField(max_length=512)),
                ('start_year', models.IntegerField(null=True)),
                ('runtime', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_rating', models.FloatField()),
                ('num_votes', models.IntegerField()),
                ('title', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='titles.title')),
            ],
        ),
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=2048)),
                ('job', models.CharField(max_length=2048)),
                ('characters', models.CharField(max_length=2048)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cast_of', to='titles.person')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crew', to='titles.title')),
            ],
        ),
        migrations.CreateModel(
            name='Aka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=2048)),
                ('region', models.CharField(max_length=15)),
                ('language', models.CharField(max_length=15)),
                ('is_original_title', models.BooleanField()),
                ('attributes', models.CharField(max_length=256)),
                ('types', models.CharField(max_length=256)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='akas', to='titles.title')),
            ],
        ),
        migrations.CreateModel(
            name='TitleGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titles', to='titles.genre')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genres', to='titles.title')),
            ],
            options={
                'unique_together': {('title', 'genre')},
            },
        ),
        migrations.CreateModel(
            name='KnownFor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='known_for', to='titles.person')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='titles.title')),
            ],
            options={
                'unique_together': {('title', 'person')},
            },
        ),
    ]
