# Generated by Django 3.2.15 on 2022-09-09 02:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('titles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userrating',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='titlegenre',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titles', to='titles.genre'),
        ),
        migrations.AddField(
            model_name='titlegenre',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genres', to='titles.title'),
        ),
        migrations.AddField(
            model_name='rating',
            name='title',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='titles.title'),
        ),
        migrations.AddField(
            model_name='knownfor',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='known_for', to='titles.person'),
        ),
        migrations.AddField(
            model_name='knownfor',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='titles.title'),
        ),
        migrations.AddField(
            model_name='crew',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cast_of', to='titles.person'),
        ),
        migrations.AddField(
            model_name='crew',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crew', to='titles.title'),
        ),
        migrations.AddField(
            model_name='aka',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='akas', to='titles.title'),
        ),
        migrations.AlterUniqueTogether(
            name='userrating',
            unique_together={('user', 'title')},
        ),
        migrations.AlterUniqueTogether(
            name='titlegenre',
            unique_together={('title', 'genre')},
        ),
        migrations.AlterUniqueTogether(
            name='knownfor',
            unique_together={('title', 'person')},
        ),
    ]
