# Generated by Django 3.2.15 on 2022-10-12 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0002_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userrating',
            index=models.Index(fields=['user', 'title'], name='titles_user_user_id_805ebb_idx'),
        ),
    ]
