# Generated by Django 3.2.15 on 2022-08-26 03:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("titles", "0003_alter_rating_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userrating",
            name="rating",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ]
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userrating",
            unique_together={("user", "title")},
        ),
    ]
