# Generated by Django 3.2.15 on 2022-09-28 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0003_alter_genre_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={},
        ),
    ]
